sudo: false
os:
  - linux
  - osx
language: node_js
arch:
  - amd64
  - ppc64le
node_js:
  - node
  - iojs
  - '9'
  - '8'
  - '7'
  - '6'
  - '5'
  - '4'
  - '12'
  - '10'
matrix:
  allow_failures:
    - node_js: '8'
  fast_finish: true
